# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    21sh.ebnf                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lportay <lportay@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/12/28 15:11:18 by lportay           #+#    #+#              #
#    Updated: 2018/01/16 15:55:53 by lportay          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

%token WORD
%token ASSIGNMENT_WORD

%token NEWLINE
/*     '\n'   */

%token OR  AND  SEMICOL
/*     '|' '&'    ';' */

%token IO_NUMBER
/*	 string only made of digits delimited by '<' or '>' */

%token LESS GREAT
/*      '<'  '>' */

%token  AND_IF OR_IF
/*       '&&'   '||' */

%token  DLESS  DGREAT  LESSAND  GREATAND  
/*      '<<'   '>>'    '<&'     '>&'    */ 

command 		:	statement_list NEWLINE
				|	NEWLINE
				;

statement_list	:	statement_block {SEMICOL statement_block|EMPTY}
				;

statement_block	:	statement {and_or statement_block}
				;

statement	:	io_close|io_redirect|wordlist {statement}
			;

and_or		:	OR_IF
			|	AND_IF
			|	OR
			;

wordlist	:	WORD|ASSIGNMENT_WORD {wordlist}
			;

io_redirect :	{IO_NUMBER} LESS WORD
			|	{IO_NUMBER} GREAT WORD
			|	{IO_NUMBER} DLESS WORD
			|   {IO_NUMBER} DGREAT WORD
			|	{IO_NUMBER} LESSAND	WORD
			;   {IO_NUMBER} GREATAND WORD
